name: CI Pipeline  # Name of the pipeline

# Specify when the workflow should run
on:
  push:  # Trigger pipeline when pushing to 'main' branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Run this job on the latest Ubuntu environment

    steps:
      - name: Checkout code  # Step 1: Checkout code from the repository
        uses: actions/checkout@v2

      - name: Set up Python  # Step 2: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies  # Step 3: Install required Python dependencies directly
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas

      - name: Run tests  # Step 4: Run the test file
        run: |
          python test_model.py
